[workspace]
resolver = "2"
members = ["crates/fuide", "crates/fuide-3d", "apps/file-manager", "apps/brew", "apps/player", "apps/activity-monitor", "apps/cad"]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"

[workspace.dependencies]
egui = "0.36.1"
eframe = { version = "0.36.1", default-features = false, features = ["default_fonts", "wgpu"] }
fuide = { path = "crates/fuide" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
